# Generated by Django 2.1.7 on 2019-03-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(primary_key=True, max_length=50, serialize=False)),
                ('hostname', models.TextField(max_length=20)),
                ('version', models.PositiveSmallIntegerField()),
                ('puerto', models.IntegerField()),
                ('grupo', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=1000)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Agent')),
            ],
        ),
    ]
