# Generated by Django 2.1.7 on 2019-05-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_agent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, null=True)),
                ('version', models.PositiveSmallIntegerField(null=True)),
                ('puerto', models.IntegerField(null=True)),
                ('grupo', models.CharField(max_length=50, null=True)),
                ('os', models.CharField(max_length=250, null=True)),
                ('interfaces', models.PositiveSmallIntegerField(null=True)),
                ('ubicacion', models.TextField(null=True)),
                ('archivo', models.TextField(null=True)),
            ],
        ),
    ]
