# Generated by Django 2.1.7 on 2019-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190528_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='contacto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='getway',
            field=models.CharField(default='192.168.202.15', max_length=200),
            preserve_default=False,
        ),
    ]
